# Generated by Django 5.0.7 on 2024-08-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='photo',
            field=models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='URL'),
        ),
    ]
