# Generated by Django 5.0.7 on 2024-08-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_banned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
