# Generated by Django 5.0.7 on 2024-08-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_is_published_alter_productimages_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='photo',
            field=models.ImageField(upload_to='products/%Y/%m/%d', verbose_name=''),
        ),
    ]
