# Generated by Django 5.0.7 on 2024-08-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productimages_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='caption',
        ),
    ]
