# Generated by Django 5.0.7 on 2024-08-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photoCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, upload_to='products/%Y/%m/%d', verbose_name='Фото товара'),
        ),
    ]
