# Generated by Django 5.0.7 on 2024-08-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_photocode_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photoCode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
