# Generated by Django 5.0.7 on 2024-08-02 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_options_product_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-rating',)},
        ),
    ]
